import type { ProviderCapability, ProviderManifest, ProviderStoredConfig } from "./types";

export const providerManifests: ProviderManifest[] = [
  {
    id: "minimax",
    adapterId: "minimax",
    name: "MiniMax",
    description: "Native MiniMax integration for text and image generation.",
    capabilities: ["text", "image"],
    defaultBaseUrl: "https://api.minimax.io",
    defaultModels: {
      text: "MiniMax-M2.7",
      image: "image-01",
    },
    modelOptions: {
      text: ["MiniMax-M2.7", "MiniMax-M2.7-highspeed"],
      image: ["image-01"],
    },
    modelDiscovery: true,
    docsUrl: "https://www.minimax.io/platform/document",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["text", "image"],
    tags: ["native", "text", "image"],
  },
  {
    id: "openai",
    adapterId: "openai-compatible",
    name: "OpenAI",
    description: "OpenAI Responses-compatible chat and image generation through the /v1 API.",
    capabilities: ["text", "image"],
    defaultBaseUrl: "https://api.openai.com/v1",
    defaultModels: {
      text: "gpt-4.1-mini",
      image: "gpt-image-1.5",
    },
    modelOptions: {
      text: ["gpt-5.1", "gpt-5-mini", "gpt-4.1", "gpt-4.1-mini", "gpt-4o", "gpt-4o-mini"],
      image: ["gpt-image-1.5", "gpt-image-1", "gpt-image-1-mini", "dall-e-3", "dall-e-2"],
    },
    modelDiscovery: true,
    docsUrl: "https://platform.openai.com/docs/api-reference",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["text", "image"],
    tags: ["native", "text", "image"],
  },
  {
    id: "openai-compatible",
    adapterId: "openai-compatible",
    name: "OpenAI Compatible",
    description: "Generic /v1-compatible API for OpenAI-style local servers and hosted hubs.",
    capabilities: ["text", "image"],
    defaultBaseUrl: "https://api.openai.com/v1",
    defaultModels: {
      text: "gpt-4o-mini",
      image: "gpt-image-1",
    },
    modelOptions: {
      text: ["gpt-4o-mini", "gpt-4.1-mini", "llama-3.3-70b-versatile", "deepseek-chat"],
      image: ["gpt-image-1.5", "gpt-image-1", "gpt-image-1-mini", "dall-e-3", "dall-e-2", "black-forest-labs/FLUX.1-schnell"],
    },
    modelDiscovery: true,
    docsUrl: "https://platform.openai.com/docs/api-reference",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["text", "image"],
    tags: ["custom", "text", "image"],
  },
  {
    id: "azure-openai",
    adapterId: "openai-compatible",
    name: "Azure OpenAI",
    description: "Azure OpenAI deployments. Use a deployment base URL ending in /openai/deployments/{deployment}.",
    capabilities: ["text", "image"],
    defaultBaseUrl: "https://YOUR_RESOURCE.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT",
    defaultModels: {
      text: "gpt-4.1-mini",
      image: "gpt-image-1",
    },
    modelOptions: {
      text: ["gpt-5-mini", "gpt-4.1", "gpt-4.1-mini", "gpt-4o", "gpt-4o-mini"],
      image: ["gpt-image-1.5", "gpt-image-1", "gpt-image-1-mini", "dall-e-3", "dall-e-2"],
    },
    modelDiscovery: false,
    docsUrl: "https://learn.microsoft.com/azure/ai-services/openai/",
    authHeader: "api-key",
    requiresModelFor: ["text", "image"],
    extraDefaults: {
      apiVersion: "2024-10-21",
    },
    tags: ["native", "text", "image"],
  },
  {
    id: "anthropic",
    adapterId: "anthropic",
    name: "Anthropic",
    description: "Claude Messages API for text generation.",
    capabilities: ["text"],
    defaultBaseUrl: "https://api.anthropic.com",
    defaultModels: {
      text: "claude-sonnet-4-6",
    },
    modelOptions: {
      text: ["claude-sonnet-4-6", "claude-opus-4-1", "claude-3-7-sonnet-latest", "claude-3-5-haiku-latest"],
    },
    modelDiscovery: true,
    docsUrl: "https://docs.anthropic.com/en/api/messages",
    authHeader: "x-api-key",
    requiresModelFor: ["text"],
    tags: ["native", "text"],
  },
  {
    id: "gemini",
    adapterId: "gemini",
    name: "Gemini",
    description: "Google Gemini generateContent API for text generation.",
    capabilities: ["text"],
    defaultBaseUrl: "https://generativelanguage.googleapis.com",
    defaultModels: {
      text: "gemini-3-flash-preview",
    },
    modelOptions: {
      text: ["gemini-3-pro-preview", "gemini-3-flash-preview", "gemini-2.5-pro", "gemini-2.5-flash"],
    },
    modelDiscovery: true,
    docsUrl: "https://ai.google.dev/gemini-api/docs/text-generation",
    authHeader: "x-goog-api-key",
    requiresModelFor: ["text"],
    tags: ["native", "text"],
  },
  {
    id: "openrouter",
    adapterId: "openai-compatible",
    name: "OpenRouter",
    description: "OpenAI-compatible text gateway for many hosted models.",
    capabilities: ["text"],
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    defaultModels: {
      text: "openai/gpt-4.1-mini",
    },
    modelOptions: {
      text: [
        "openai/gpt-5.1",
        "anthropic/claude-sonnet-4.5",
        "google/gemini-3-pro-preview",
        "deepseek/deepseek-chat-v3.1",
        "qwen/qwen3-coder",
      ],
    },
    modelDiscovery: true,
    docsUrl: "https://openrouter.ai/docs",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["text"],
    tags: ["hub", "text"],
  },
  {
    id: "groq",
    adapterId: "openai-compatible",
    name: "Groq",
    description: "OpenAI-compatible low-latency text generation.",
    capabilities: ["text"],
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    defaultModels: {
      text: "llama-3.3-70b-versatile",
    },
    modelOptions: {
      text: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "openai/gpt-oss-120b", "qwen/qwen3-32b"],
    },
    modelDiscovery: true,
    docsUrl: "https://console.groq.com/docs",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["text"],
    tags: ["preset", "text"],
  },
  {
    id: "together",
    adapterId: "openai-compatible",
    name: "Together AI",
    description: "OpenAI-compatible hosted open model provider with text and FLUX image endpoints.",
    capabilities: ["text", "image"],
    defaultBaseUrl: "https://api.together.xyz/v1",
    defaultModels: {
      text: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
      image: "black-forest-labs/FLUX.1-schnell",
    },
    modelOptions: {
      text: [
        "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "deepseek-ai/DeepSeek-V3",
        "Qwen/Qwen3-235B-A22B-fp8-tput",
      ],
      image: ["black-forest-labs/FLUX.1-schnell", "black-forest-labs/FLUX.1-dev"],
    },
    modelDiscovery: true,
    docsUrl: "https://docs.together.ai/docs/openai-api-compatibility",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["text", "image"],
    tags: ["preset", "hub", "text", "image"],
  },
  {
    id: "deepseek",
    adapterId: "openai-compatible",
    name: "DeepSeek",
    description: "OpenAI-compatible DeepSeek chat models.",
    capabilities: ["text"],
    defaultBaseUrl: "https://api.deepseek.com/v1",
    defaultModels: {
      text: "deepseek-chat",
    },
    modelOptions: {
      text: ["deepseek-chat", "deepseek-reasoner"],
    },
    modelDiscovery: false,
    docsUrl: "https://api-docs.deepseek.com",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["text"],
    tags: ["native", "text"],
  },
  {
    id: "ollama",
    adapterId: "openai-compatible",
    name: "Ollama",
    description: "Local Ollama OpenAI-compatible API on loopback.",
    capabilities: ["text"],
    defaultBaseUrl: "http://127.0.0.1:11434/v1",
    defaultModels: {
      text: "llama3.2",
    },
    modelOptions: {
      text: ["llama3.2", "llama3.1", "qwen2.5-coder", "mistral", "gemma3"],
    },
    modelDiscovery: true,
    docsUrl: "https://ollama.com/blog/openai-compatibility",
    authHeader: "none",
    requiresModelFor: ["text"],
    tags: ["local", "text"],
  },
  {
    id: "lm-studio",
    adapterId: "openai-compatible",
    name: "LM Studio",
    description: "Local LM Studio OpenAI-compatible server.",
    capabilities: ["text"],
    defaultBaseUrl: "http://127.0.0.1:1234/v1",
    defaultModels: {
      text: "local-model",
    },
    modelOptions: {
      text: ["local-model", "qwen2.5-coder", "llama-3.2", "mistral-small"],
    },
    modelDiscovery: true,
    docsUrl: "https://lmstudio.ai/docs/app/api",
    authHeader: "none",
    requiresModelFor: ["text"],
    tags: ["local", "text"],
  },
  {
    id: "vllm",
    adapterId: "openai-compatible",
    name: "vLLM",
    description: "Local or self-hosted vLLM OpenAI-compatible server.",
    capabilities: ["text"],
    defaultBaseUrl: "http://127.0.0.1:8000/v1",
    defaultModels: {
      text: "local-model",
    },
    modelOptions: {
      text: ["local-model", "Qwen/Qwen2.5-Coder-32B-Instruct", "meta-llama/Llama-3.1-8B-Instruct"],
    },
    modelDiscovery: true,
    docsUrl: "https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["text"],
    tags: ["local", "self-hosted", "text"],
  },
  {
    id: "local-openai",
    adapterId: "openai-compatible",
    name: "Local OpenAI-compatible",
    description: "Custom local /v1-compatible server for text or image experiments.",
    capabilities: ["text", "image"],
    defaultBaseUrl: "http://127.0.0.1:8080/v1",
    defaultModels: {
      text: "local-model",
      image: "local-image-model",
    },
    modelOptions: {
      text: ["local-model"],
      image: ["local-image-model"],
    },
    modelDiscovery: true,
    docsUrl: "https://platform.openai.com/docs/api-reference",
    authHeader: "none",
    requiresModelFor: ["text", "image"],
    tags: ["local", "custom", "text", "image"],
  },
  {
    id: "stub",
    adapterId: "stub",
    name: "Stub (placeholder)",
    description: "Deterministic local placeholder image provider for smoke tests without API keys.",
    capabilities: ["image"],
    defaultBaseUrl: "http://127.0.0.1",
    defaultModels: {
      image: "stub-image",
    },
    modelOptions: {
      image: ["stub-image"],
    },
    modelDiscovery: false,
    docsUrl: "https://github.com/nexu-io/open-design",
    authHeader: "none",
    requiresModelFor: ["image"],
    tags: ["local", "image", "stub"],
  },
  {
    id: "pollinations",
    adapterId: "pollinations",
    name: "Pollinations",
    description: "Free-tier friendly image API for smoke tests and prototypes. Use a publishable or secret Pollinations key.",
    capabilities: ["image"],
    defaultBaseUrl: "https://gen.pollinations.ai",
    defaultModels: {
      image: "flux",
    },
    modelOptions: {
      image: ["flux"],
    },
    modelDiscovery: true,
    docsUrl: "https://github.com/pollinations/pollinations/blob/main/APIDOCS.md",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["image"],
    tags: ["preset", "image", "free-tier"],
  },
  {
    id: "fal",
    adapterId: "fal",
    name: "fal.ai",
    description: "Queued image model endpoints through fal.",
    capabilities: ["image"],
    defaultBaseUrl: "https://queue.fal.run",
    defaultModels: {
      image: "fal-ai/flux/schnell",
    },
    modelOptions: {
      image: ["fal-ai/flux/schnell", "fal-ai/flux/dev", "fal-ai/flux-pro/v1.1"],
    },
    modelDiscovery: false,
    docsUrl: "https://fal.ai/docs/documentation/model-apis/inference/queue",
    authHeader: "Authorization: Key",
    requiresModelFor: ["image"],
    tags: ["native", "image", "flux"],
  },
  {
    id: "replicate",
    adapterId: "replicate",
    name: "Replicate",
    description: "Replicate model predictions for image generation.",
    capabilities: ["image"],
    defaultBaseUrl: "https://api.replicate.com",
    defaultModels: {
      image: "black-forest-labs/flux-schnell",
    },
    modelOptions: {
      image: [
        "black-forest-labs/flux-schnell",
        "black-forest-labs/flux-dev",
        "black-forest-labs/flux-pro",
        "stability-ai/sdxl",
      ],
    },
    modelDiscovery: false,
    docsUrl: "https://replicate.com/docs/topics/predictions/create-a-prediction",
    authHeader: "Authorization: Bearer",
    requiresModelFor: ["image"],
    tags: ["native", "image", "flux"],
  },
];

export const providerManifestMap = new Map(providerManifests.map((manifest) => [manifest.id, manifest]));

export function getProviderManifest(providerId: string): ProviderManifest | undefined {
  return providerManifestMap.get(providerId);
}

export function getManifestsForCapability(capability: ProviderCapability): ProviderManifest[] {
  return providerManifests.filter((manifest) => manifest.capabilities.includes(capability));
}

export function createDefaultProviderConfig(manifest: ProviderManifest): ProviderStoredConfig {
  return {
    enabled: manifest.id === "minimax" || manifest.tags?.includes("local") === true,
    apiKey: "",
    baseUrl: manifest.defaultBaseUrl,
    models: { ...manifest.defaultModels },
    customHeaders: {},
    extra: { ...manifest.extraDefaults },
  };
}
